package com.entity.enums;

public enum WaitingType {
    START, SET_FULL_NAME, SET_PHONE, YES_OR_NO,SELECT_EDUCATION,SET_CARD_ID,
    DATE_ISSUE, DATE_END,ISSUED_BY,PHOTO_CARD, PHOTO,  SET_IIN, TYPE_DIPLOMA, SELECT_GENDER,
    SELECT_NATIONALITY, SELECT_ADDRESS, SELECT_BIRTH_DATE, SET_PHONE_PARENT, SET_LANG,
    SELECT_COURSE, SELECT_COURSE_PERIOD, SELECT_SCHOOL, SELECT_SPECIALITY, SELECT_DORM,
    SELECT_DORM_ROOM,SELECT_SOCIAL_GROUP
}

