package com.entity.enums;

public enum WaitingType {
    START,

    SET_FULL_NAME, SET_PHONE_NUMBER, SET_EMAIL, SET_SUGGESTION,   // id001_Suggestion

    SET_IIN, SET_ADDRESS, SET_VISA, SET_APARTMENT, ACTION_MENU, OTHER_APARTMENT, PARENT_COUNT, SOCIAL_BENEFITS, SET_STATUS, OTHER_SOCIAL_BENEFITS, OTHER_STATUS, SET_MARITAL_STATUS, SET_ALIMENTS, EMPLOYMENT_TYPE,
    EMPLOYMENT, OTHER_EMPLOYMENT_TYPE, SET_NEED_A_JOB, EDUCATION, SET_JOB_TYPE, DISABILITY_TYPE, SET_MOTHER_FATHER_FULL_NAME, SET_CHILDREN_DISABILITY, SET_GRAND_PARENT, SET_PROF_COURSES, SET_OTHER_PROF_COURSES,
    SET_EDUCATION_AND_OTHER_COURSES, SET_OTHER_EDUCATION_AND_OTHER_COURSES, SET_BUSINESS_TRAINING, SET_OTHER_BUSINESS_TRAINING, SET_EDUCATION_COURSES_FOR_KIDS, SET_OTHER_COURSES_FOR_KIDS,
    SET_ART_AND_MUSIC_COURSES, SET_OTHER_ART_AND_MUSIC_COURSES, SET_SPORT_SECTION, SET_OTHER_SPORT_SECTION, SET_SOCIAL_NEEDS, SET_OTHER_SOCIAL_NEEDS, SET_PSYCHO_NEED, SET_LAWYER_NEED, SET_HEALER_FOR_FAMILY,
    SET_OTHER_HEALER_FOR_FAMILY, SET_CREDIT_HISTORY, SET_OTHER_CREDIT_HISTORY, SET_CREDIT_INFO, SET_EDUCATION_NAME, SET_CHILDREN, SET_CREDIT_INFO_OTHER, // id004_FirstRegistration

    SET_COURSES_TYPE, SET_COURSES_NAME, SET_COURSE, SET_HANDLING,  // id005_Courses

    SET_TRAINING_NAME, SET_TRAINING, // id006_Training

    SET_BUSINESS_NAME, SET_BUSINESS, // id007_SupportBusinessProject

    SET_SERVICE_TYPE, SET_SERVICE, SERVICE, // id008_Service

    EVENT_SELECTION, EVENT, // id009_ShowEvent

    CHOOSE_QUESTION, CHOOSE_OPTION, SET_TEXT, // id010_Survey

    COMMAND_EDITOR, UPDATE_BUTTON, UPDATE_TEXT, UPDATE_FILE, NEXT_KEYBOARD, UPDATE_BUTTON_LINK, // id012_EditMenu

    SET_NAME_RU, SET_NAME_KZ, SET_TEXT_RU, SET_TEXT_KZ, SET_ANSWER_OF_QUEST_RU, SET_ANSWER_OF_QUEST_KZ, SET_MESSAGE_RU, SET_MESSAGE_KZ, // id013_AddSurvey

    EDITION, UPDATE_QUEST, UPDATE_MESSAGE, EDITION_MESSAGE, SET_RANGE, SET_MESSAGE, DELETE_MESSAGE, SET_NAME, SET_DESCRIPTION, DELETE, GET_RANGE, GET_MESSAGE, // id014_EditSurvey

    CHOOSE_COURSES_VARIANT, SEND_IIN, START_DATE, END_DATE,

    SET_DATE,

    CHOOSE_EVENT, NEW_EVENT, SET_PHOTO, SET_TEXT_EVENT,

    COURSE_MENU, COURSES_TYPE, EDIT_COURSES, NEW_COURSES,

    SET_CONSULTATION_TYPE, SET_CONSULTATION_NAME, SET_CONSULTATION,

    SET_COMPLAINT, CHOOSE_GROUP,
    EDIT_TAG, SERVICE_TYPE_OPTION, COURSE_NAME_OPTION, TRAINING_NAME_OPTION, BUSINESS_NAME_OPTION, CONSULTATION_NAME_OPTION, EDITION_CHOICE,
    HANDLING_EMPLOYEE,INVITE_DATE,INVITE_TIME,THIS_PERSON_OR_NO,






    CHOOSE_CATEGORY,CHOOSE_SERVICE_OR_EDIT_CATEGOR,DELETE_OR_EDIT_CATEGOR,SET_NEW_NAME_CATEGORY_KAZ,SET_NEW_NAME_CATEGORY_RUS,
    SET_SERVICE_NAME_KAZ,SET_SERVICE_NAME_RUS,SET_MODE_SERVICE,
    CHOOSE_SPEC,SET_DESC_SERVICE_KAZ, SET_DESC_SERVICE_RUS,SET_AFISHA,ADD_OR_EDIT_SERVICE_AND_ADD_OR_DELETE_SPEC_OR_EDIT_DESC,
    SET_NEW_NAME_SERVICE_KAZ,SET_NEW_NAME_SERVICE_RUS,CONFIRM_DELETE_SERVICE,SET_NEW_PHOTO_SERVICE,SET_NEW_DESC_SERVICE_KAZ,
    SET_NEW_DESC_SERVICE_RUS,CHOOSE_SPEC_FOR_EDIT,CHOOSE_OPTION_EDIT_SPEC,SET_NEW_NAME_SPEC,SET_NEW_PHOTO_SPEC,
    SET_NEW_DESC_SPEC_KAZ,SET_NEW_DESC_SPEC_RUS,

    CHOOSE_SERVICE,LIST_REGISTR_OR_ADD_DIRECTION,REGISTER_TO_SPEC,

    SET_NAME_SPEC,SET_DESC_SPEC_KAZ,SET_PHOTO_SPEC,SET_DESC_SPEC_RUS,SET_CONTACT_SPEC,

    SET_KAZ_NAME_DIRECTION,SET_RUS_NAME_DIRECTION,DELETE_DIRECTION,SET_NEW_RUS_NAME_DIRECTION,SET_NEW_KAZ_NAME_DIRECTION,
    CHOOSE_DIRECTION,CHOOSE_DIRECTION_OR_NEXT,CHOOSE_LIST_OR_ADD_REPORT,SET_TEXT_REPORT_OF_SERVICE,SEND_REPORT,

    SET_IIN_FOR_REQUEST,CHOOSE_OPTION_FOR_SPEC,CHOOSE_OPTION_FOR_SERVICE,CONFIRM_DELETE,CHOOSE_OPTION_FOR_RE_REGISTRATION,
    YES_NO
}
